#pragma once

#include <filesystem>
#include <string>
#include <unordered_set>

class EntityRegistry;
class RefVariant;

class MarkdownGenerator {
public:
  /**
    * Constructor.
    *
    * @param output Output directory.
    */
  MarkdownGenerator(const std::filesystem::path& output): output(output) {}

  /**
    * Generate documentation.
    *
    * @param root Root entity.
    * @param cov Include code coverage report?
    */
  void generate(const EntityRegistry& registry, const bool cov);

  /**
    * Clean up after generation, removing files from old runs. Traverses the
    * output directory, removing any Markdown files with 'generator: doxide' in
    * their YAML frontmatter that were not generated by previous calls of
    * `generate()`.
    */
  void clean();

private:
  void render_entity(const EntityRegistry& registry, const std::filesystem::path& output, const RefVariant& root, const std::string& sanitized_name, bool cov);


  /**
   * Output directory.
   */
  std::filesystem::path output;

  /**
   * Set of files generated during the last call to generate().
   */
  std::unordered_set<std::filesystem::path> files;

};
